### ISSUE TITLE
customize labels in github

### ISSUE THREAD

**Issue by koray-bostanci** [SWE574-TeamUnity/RepoUnity#1]
We've talked about using labels in order to mark and group issues.
Here are my suggestions.

- priority-low
- priority-moderate
- priority-high

- architecture
- design
- infrastructure
- deployment
- configuration

- backend-development
- web-development
- mobile-development
- testing
- bug

- planning
- documentation
- discussion
- research

**Comment by onatbas** [comment]
I agree with this.

**Comment by eylulakar** [comment]
I also agree. Additionally, I suggest adding these two:

-analysis - we might have a long phase of analysis since we experienced in 573. :)
-enhancement - I needed this label on my 573 project. It referred things that could take time additionally; anything related to additional development, refactoring, just visual adjustments etc.

**Comment by koray-bostanci** [comment]
Ok, I've created the labels including the ones @eylulakar suggested. The labels that @NurErtem has created before are also in our list.

I'm closing this issue but it's always possible to add new labels if there is a new need.

**Comment by NurErtem** [comment]
when there are lots of labels, it becomes hard to find which one to track and also since they are in alphabetical order related ones become so far apart, if we chane the naming conventions like axxxxx bxxxx for the ones which are related it becomes easier to pick, it is just a detail.
