### ISSUE TITLE
Deciding on Server OS

### ISSUE THREAD

**Issue by bozavci** [SWE574-TeamUnity/RepoUnity#12]
Lets decide on which OS to use in our server which will be deployed on AWS based on discussion #3  

I will suggest Debian Server 8 but I am very open to other alternatives since our requirements for OS are very trivial. What do you think ?

**Comment by onatbas** [comment]
Debian+Tomcat is fine with me.

**Comment by NurErtem** [comment]
in the previous project i used free tier aws with the following listed.  since i am not familiar with the best practices for java. i leave it up to the ones who knows. I can definetly help with deployment and production on aws. I use windows. most of you use mac. so the processes and tools are bit different. 
Python3.5 as the OO programming language
 	Django as the web framework
 	Django-Rest 
 	Django requests 
 	SQLite as the default database storage
 	64-bit Ubuntu Linux free tier in AWS with Apache2 web server

**Comment by koray-bostanci** [comment]
Since we chosed Java+Spring for the backend development stack on issue #2, any Debian/GNU Linux based OS fits for us. It does not make too much difference in our scope using Debian or Ubuntu.

So, I agree with the choice Debian.

**Comment by bozavci** [comment]
Closing as Debian. Please re-open if any objections.
