### ISSUE TITLE
which technology stack on backend should we choose?

### ISSUE THREAD

**Issue by koray-bostanci** [SWE574-TeamUnity/RepoUnity#2]
As it's mentioned today in class, there are 2 options as the primary programming language; Java and Python. They also have different frameworks alternatives.

Which one should we use? What are your previous experiences with these languages, frameworks and environments?

Let's discuss and choose the primary development environment that best fits the project and our team.

**Comment by bozavci** [comment]
I am open to develop with both languages but for python i would suggest frask instead of django. If we decide to continue with java I would prefer spring but again open to other frameworks.

**Comment by onatbas** [comment]
This discussion is I think about backend development. I'd say Django. Django has everything built in and easy to program with. Many of us has experience with it from previous project. I have no idea about frask. If we decide on Java, I suggest spring as well. But my vote is not on python, it's on django to be precise.

**Comment by onatbas** [comment]
I took the liberty of changing the title to backend, as Koray's description was specifically on Java vs. Python, which is a limitation for backend only.

**Comment by eylulakar** [comment]
I'd prefer Java for backend, since I'm already familiar with it and Spring framework also. Previously I developed a few small-scaled mobile and web applications using Java, and because it's very similar to my working environment(asp.net) I'd be more comfortable and effective using it.
I have no experience on phyton but since you mention it's an easy language and environment, I'd be okay to go with it eventually.

**Comment by atabn** [comment]
I have experience with Java & Spring, so these would be my first choice.
I don't have any experience with Python and its frameworks.

**Comment by bozavci** [comment]
Agreed on Java + Spring. If anyone objects please re-open.
