### ISSUE TITLE
Decide on board structure

### ISSUE THREAD

**Issue by onatbas** [SWE574-TeamUnity/RepoUnity#7]
As decided the board is created here, https://github.com/SWE574-TeamUnity/RepoUnity/projects/2

I just added default columns Open, In Progress, Done. How should we deal with statuses there? Any ideas? Any other columns?

**Comment by bozavci** [comment]
I think we should separate done into testing and live.

Testing : An issue we finished development but not in master branch and live project.
Live : An issue closed and live in project.

Otherwise definition of "done" becomes an issue.

**Comment by onatbas** [comment]
Sounds good. What about on tasks that are unrelated to code? Should we skip testing and just move to live on that kind of situation?

**Comment by koray-bostanci** [comment]
I think **_testing_** will be very important in this project. Because when we start development, probably every team member will develop a part of the application and it's very important that we should guarantee every unique part (maybe a new feature) is working independently and also does not break the whole application or system. So unit tests and integration tests should be a part of our development process.

Dividing "Done" into 2 parts is a decision of course. But the answer is "it depends" I think. 
If we create two tasks for developing a feature "Task1 : Implementing Feature1" and "Task2 : Writing unit tests for Feature1". Then these 2 tasks can be in same or different statuses. In this case, may be there is no need to have a separate "Testing" status because if someone asks "what is the status of testing Feature1?", some can say it's In Progress or Done by checking the status of Task2. Implementation and Testing can be separate tasks and may be assigned to same or different assignees.

On the other hand, having a separate "Testing" status helps us to easily see and monitor which tasks are on testing.

So, I suggest the following names for statuses but actually I'm ok with other naming conventions too.

- Backlog
- In Progress
- Testing
- Done

**Comment by onatbas** [comment]
I agree, let's rename Live to Done and it's alright. By convention Done is more explicit and it will help on the issue I adressed preciously.

**Comment by onatbas** [comment]
@koray-bostanci Btw, I th'nk there's no need for backlog. If you look at the github projects and issues, you'll see that the issues that are created aren't immediately added to the board. You have to explicitly add them to board. So in my pov, the issues that aren't added to board are the backlog. 

You can actually unadded files by clicking  "Add Cards". so I propose renaming Backlog to Open. Open should stand for something l'ke "in the scope of current iteration". And "in progress" for actively working.

@bozavci @koray-bostanci what are your thoughts? I th'nk after a couple of iterations we can close this issue and come to an agreement.

**Comment by bozavci** [comment]
I agree but there is a slight difference between created and backlog because anyone can create an issue but maybe someone disagrees with that task. Where in backlog we all agree that issue needs to be done but again this difference will occur according to the way we create issues. If we create issues together during our meetings there wont be any difference between created and backlog.

**Comment by koray-bostanci** [comment]
@onatbas Ok, we can assume that all the issues that are not in board are in our "Backlog".
But we still need a separate status for the issues that are in our work item list (board) and still not started. So we can rename the "Backlog" to "Open". This naming fits better in this approach. And "Backlog" means the issues that are not in board for now but will be probably on board in future sprints.

**Comment by onatbas** [comment]
Exactly my thoughts. 

So this brings us to this conclusion, 

- (not in board) - Issue exists in the Issues page, yet  it's accepted or added to current iteration
- Open  - Scheduled for this iteration. Currently, not in progress.
- In Progress - Actively working on it
- Testing - Work is complete, awaiting acceptance
- Done - Accepted & merged or completed.

Sounds good?

**Comment by NurErtem** [comment]
one more thing could we keep all issues in the board to have a high level overview? does it make sense or not?

**Comment by onatbas** [comment]
Let's close this issue as team agreed upon the board structure. @bozavci created the board structure, thanks! 
We might create another issue for "One repository vs. Multiple repositories" discussion.
If you have any concerns, please re-open the issue.
